id_col_name: "ID"
target_col_name: "SMILES_substrate_canonical_no_stereo"
split_col_name: "Fold"
type_col_name: "Type"
class_names: ["isTPS"]
optimize_hyperparams: false
random_state: 0
hyperparam_dimensions: none
seq_col_name: "Aminoacid_sequence"
n_calls_hyperparams_opt: 0
bitscore: 25
n_jobs: 64
root_path_to_models: "data/supfam_models"
working_directory: "supfam_temp"
neg_val: "Unknown"
negatives_sample_path: "data/sampled_id_2_seq.pkl"
tps_cleaned_csv_path: "data/EnzymeExplorer_Dataset.csv"
per_class_optimization: false
reuse_existing_partial_results: false
load_per_class_params_from: ""
enable_distractors: false
