id_col_name: "ID"
target_col_name: "SMILES_substrate_canonical_no_stereo"
split_col_name: "Fold"
type_col_name: "Type"
class_names: ["CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "precursor substr",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC=C(C)CCC=C(C)CCC1OC1(C)C",
            "CC1(C)CCCC2(C)C1CCC(=C)C2CCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O.CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O.CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "isTPS"]
optimize_hyperparams: false
random_state: 0
hyperparam_dimensions: none
seq_col_name: "Aminoacid_sequence"
n_calls_hyperparams_opt: 0
search_e_threshold: 1e-3
n_jobs: 64
pred_batch_size: 32
zero_conf_level: 10
group_column_name: "Kingdom"
neg_val: "Unknown"
negatives_sample_path: "data/sampled_id_2_seq.pkl"
tps_cleaned_csv_path: "data/EnzymeExplorer_Dataset.csv"
per_class_optimization: false
reuse_existing_partial_results: false
load_per_class_params_from: ""
