id_col_name: "Uniprot ID"
target_col_name: "SMILES_substrate_canonical_no_stereo"
split_col_name: "stratified_phylogeny_based_split_with_minor_products"
class_names: ["CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "precursor substr",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC=C(C)CCC=C(C)CCC1OC1(C)C",
            "CC1(C)CCCC2(C)C1CCC(=C)C2CCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O.CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O.CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "isTPS"]
optimize_hyperparams: true
random_state: 0
n_calls_hyperparams_opt: 350
hyperparam_dimensions:
  reg_lambda:
    type: "float"
    args: [1, 100.0, "uniform"]
  gamma:
    type: "float"
    args: [1.0e-6, 0.5, "uniform"]
  max_depth:
    type: "int"
    args: [1, 100, "uniform"]
  subsample:
    type: "float"
    args: [0.7, 1.0, "log-uniform"]
  colsample_bytree:
    type: "float"
    args: [0.7, 1.0, "log-uniform"]
  scale_pos_weight:
    type: "float"
    args: [1.0e-6, 30.0, 'uniform']
  min_child_weight:
    type: "int"
    args: [1, 10]
  n_estimators:
    type: "int"
    args: [20, 400, "uniform"]
  max_train_negs_proportion:
    type: "float"
    args: [0.5, 0.99, "log-uniform" ]
n_jobs: -1
objective: "binary:logistic"
booster: "gbtree"
reg_lambda: 1
gamma: 2.0e-6
max_depth: 6
subsample: 1.0
colsample_bytree: 1.0
scale_pos_weight: 1
min_child_weight: 1
n_estimators: 50
max_train_negs_proportion: 0.98
neg_val: "Unknown"
save_trained_model: true
negatives_sample_path: "data/sampled_id_2_seq.pkl"
tps_cleaned_csv_path: "data/TPS-Nov19_2023_verified_all_reactions_with_neg_with_folds.csv"
per_class_optimization: false
reuse_existing_partial_results: false
load_per_class_params_from: ""
