include: ../main_config.yaml
per_class_optimization: false
# requires_multioutputwrapper_for_multilabel: true
optimize_hyperparams: true
n_calls_hyperparams_opt: 50
domain_dist_path: "data/enzyme_explorer_structural_features/domain_dist_based_features.pkl"
reuse_existing_partial_results: true
