reference-domains-file-path: "data/detected_domains/martsDB_detected_domains/martsDB_detected_domains.pkl"
reference-domains-structures-directory: "data/detected_domains/martsDB_detected_domains/domains/"
query-domains-file-path: "data/detected_domains/enzyme_explorer_detected_domains/enzyme_explorer_detected_domains.pkl"
query-domains-structures-directory: "data/detected_domains/enzyme_explorer_detected_domains/domains/"
output-directory: "data/enzyme_explorer_structural_features"