id_col_name: "Uniprot ID"
target_col_name: "SMILES_substrate_canonical_no_stereo"
split_col_name: "stratified_phylogeny_based_split_with_minor_products"
class_names: ["isTPS"]
optimize_hyperparams: false
random_state: 0
hyperparam_dimensions: none
seq_col_name: "Amino acid sequence"
n_calls_hyperparams_opt: 0
e_threshold: 10
n_jobs: 64
root_path_to_models: "data/pfam_models"
working_directory: "pfam_temp"
neg_val: "Unknown"
negatives_sample_path: "data/sampled_id_2_seq.pkl"
tps_cleaned_csv_path: "data/TPS-Nov19_2023_verified_all_reactions_with_neg_with_folds.csv"
per_class_optimization: false
reuse_existing_partial_results: false
load_per_class_params_from: ""
