id_col_name: "Uniprot ID"
target_col_name: "SMILES_substrate_canonical_no_stereo"
split_col_name: "stratified_phylogeny_based_split_with_minor_products"
class_names: ["CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "precursor substr",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC=C(C)CCC=C(C)CCC1OC1(C)C",
            "CC1(C)CCCC2(C)C1CCC(=C)C2CCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O.CC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O.CC(C)=CCCC(C)=CCCC(C)=CCCC(C)=CCOP([O-])(=O)OP([O-])([O-])=O",
            "isTPS"]
optimize_hyperparams: true
random_state: 0
n_calls_hyperparams_opt: 15
hyperparam_dimensions:
  penalty:
    type: "categorical"
    args: [ 'l1', 'l2' ]
  tol:
    type: "float"
    args: [ 0.000001, 0.01, "log-uniform" ]
  C:
    type: "float"
    args: [ 0.0001, 1000, "log-uniform" ]
  max_iter:
    type: "int"
    args: [ 100, 200, "uniform" ]
penalty: "l2"
tol: 0.0001
C: 1.0
max_iter: 100
solver: "saga"
max_train_negs_proportion: 0.98
neg_val: "Unknown"
save_trained_model: true
negatives_sample_path: "data/sampled_id_2_seq.pkl"
tps_cleaned_csv_path: "data/TPS-Nov19_2023_verified_all_reactions_with_neg_with_folds.csv"
per_class_optimization: true
reuse_existing_partial_results: false
load_per_class_params_from: ""
requires_multioutputwrapper_for_multilabel: true
